# Generated by Django 4.1.3 on 2022-11-16 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_phone_number_alter_user_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='pet_name',
        ),
        migrations.RemoveField(
            model_name='services',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Pet',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
