# Generated by Django 4.1.3 on 2023-02-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='wants_coat_styling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='services',
            name='wants_coat_trimming',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='services',
            name='wants_full_service',
            field=models.BooleanField(default=False),
        ),
    ]
