# Generated by Django 4.1.3 on 2023-02-18 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_services_wants_obedience_training_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='pet_name',
        ),
        migrations.RemoveField(
            model_name='services',
            name='wants_coat_styling',
        ),
        migrations.RemoveField(
            model_name='services',
            name='wants_coat_trimming',
        ),
        migrations.RemoveField(
            model_name='services',
            name='wants_full_service',
        ),
        migrations.RemoveField(
            model_name='services',
            name='wants_obedience_training',
        ),
        migrations.RemoveField(
            model_name='services',
            name='wants_performance_training',
        ),
        migrations.RemoveField(
            model_name='services',
            name='wants_protection_training',
        ),
    ]
