# Generated by Django 4.1.3 on 2023-02-06 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_rename_text_comment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='dogName',
            new_name='dog_name',
        ),
    ]
