# Generated by Django 4.1.3 on 2022-12-10 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='user',
            new_name='owner',
        ),
    ]
