# Generated by Django 4.1.3 on 2022-12-12 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_pet_breed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='owner',
            new_name='user',
        ),
    ]
