# Generated by Django 4.1.3 on 2022-12-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_rename_owner_pet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='wants_coat_styling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pet',
            name='wants_coat_trimming',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pet',
            name='wants_full_service',
            field=models.BooleanField(default=False),
        ),
    ]
