# Generated by Django 4.1.3 on 2023-02-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0006_remove_pet_wants_coat_styling_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='owner_name',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
