# Generated by Django 4.1.3 on 2023-02-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0007_pet_owner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='owner_name',
            field=models.CharField(default='blank', max_length=255),
        ),
    ]
