# Generated by Django 4.1.3 on 2023-02-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0009_pet_wants_coat_styling_pet_wants_coat_trimming_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='wants_full_service',
            field=models.BooleanField(default=False),
        ),
    ]
